### ISSUE TITLE
UH_1

### ISSUE THREAD

**Issue by MariaBelen1** [ISPC-TST-ELECTRONICA-MICROCONTROLADA/proyecto-2-grupo-02#14]
Ejercicio #1, lógica combinacional: 01/05 al 14/05
Diseñar un controlador de display 7 segmentos utilizando un decodificador
BCD a 7 segmentos y un circuito combinacional que convierta la entrada
decimal en formato BCD. El controlador debe ser capaz de mostrar la entrada
decimal en el display.
**Desarrollo del  ejercicio 1 **

a)-Se va a utilizar un simulador donde el SM @emma22xt  dejara una plantilla sobre la cual se iran definiendo las funciones para cada segmento. Una vez completada se debe solicitar Pullrequest

b) Generar la documentación sobre la forma de trabajo 

UH_1 Como PO @MariaBelen1  deseo implementar en proteus un codificador según Ej 

UH#1TK1_PO: @MariaBelen1 : Definir Product Backlog

UH#1TK2_SM: @emma22xt  Crear estructura de repositorio

UH#1TK3_SM: @emma22xt Crear proyecto Kanban

UH#1TK4_ST: @777dem27med03-125 , @Leantrivellini , @Brunonbt Crear Documentación Sobre la Forma de Trabajo 

UH#1TK5_ST: @Maxg8704 , @MicaelaVilchez Crear Solución Hardware Para el SEG A

UH#1TK6_ST: @NahuelDe , @MrGuz2022 @suarezignacio @RiosLionel  Crear Solución Hardware para el Segmento G

**Comment by 777dem27med03-125** [comment]
Perfecto, estoy en ello. En crear Documentación sobre la forma de trabajo.

**Comment by Maxg8704** [comment]
> 

Agregue Solucion de Hardware para segmento A en carpeta Proyecto>Hardware.
