### ISSUE TITLE
Diseñar un controlador de display 7 segmentos utilizando un decodificador BCD a 7 segmentos y un circuito combinacional que convierta la entrada decimal en formato BCD. El controlador debe ser capaz de mostrar la entrada decimal en el display.

### ISSUE THREAD

**Issue by MariaBelen1** [ISPC-TST-ELECTRONICA-MICROCONTROLADA/proyecto-2-grupo-02#3]

**Comment by MariaBelen1** [comment]
display 7 seg catodo comun
https://www.google.com/url?sa=i&url=https%3A%2F%2Fhetpro-store.com%2FTUTORIALES%2Fdisplay-7-segmentos-anodo-catodo-comun%2F&psig=AOvVaw1qED7jhFrnypnIjukaNPPU&ust=1683258926488000&source=images&cd=vfe&ved=0CBIQjhxqFwoTCJDLi6Xi2v4CFQAAAAAdAAAAABAE

**Comment by Maxg8704** [comment]
Agrego Solucion de Hardware para segmento A, en carpeta Proyecto/Hardware.
