### ISSUE TITLE
Primer_Ejercicio * lógica combinacional 

### ISSUE THREAD

**Issue by MariaBelen1** [ISPC-TST-ELECTRONICA-MICROCONTROLADA/proyecto-2-grupo-02#4]

**Comment by MicaelaVilchez** [comment]
Modelo de resolución del primer ejercicio de lógica combinacional:

![Image](https://github.com/ISPC-TST-ELECTRONICA-MICROCONTROLADA/proyecto-2-grupo-02/assets/129962506/877b342e-f8a8-442b-852b-1b9d4f95cb6c)
